language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: Yls7afmuE4e4FWIvbamNSyWVMWxQGUlSMadZ8Zu3IZzVo9v9Flon7/t6GRuoqpTHP53Oh6u/L09mzm6h69u+cD+lzR00yoRdC4s1TA4ZPJU1eRER1q0fqUFQbBTK3tg0yha2o0T9GpGrz/LxxKhIy0Q88MoFk18f8mMwsgrFSNfqEP5OC66v0Y+E0r7mZbX8m0MCuRJLI6HaXfe03h932XaodS7sPf4X4jGbYbBkDPtat7XzAg8eOZ3YerPJcVuHPiDufO7tD/ujgwiuUDv4yKnXaLiPIfQw/lgXjieNBJzn3hiBpv55q6HPyP1+WySX7Xt0MobhkfbinbXttjEbJOOT4eTbhd4G9Go5+XejY1E6iODAf+ZSdB/b3EYKdVXFCL81vN9JOYnQ9bCddQtVtohz49GDqkIXZRHUySHtt5uXSktq5mKb7QRpVASqBhQdq0RZ0fLw4JU1Jw8qkh6aAmo5ODTZvrGoCn0iofJrDMi7OONJ1MMPXiCy1OX2pR3eyXwjsAlZI6z7KnQ9U7L7hM/ipFuwASnc6DLRqfBf8PGaZKb5tnIwzaDMLR0Gzl5N63QLLVB2PSvoazeoo70BXjleuUfTh+q/1XKlA46KYx4GCm+NG16dKK3kJ3CKqcV6f+SKHzBCbANkk96adBqoRmXhGkALua7SCehWdgGoJr4=
  app: powerful-fortress-73868
  on:
    repo: esokoletsky/node-shopping-list-integration-tests
