language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: C0tjHCaWCSaYEfMNkrexd1btMjuygL2ju9f4sLu0MRphkFbWJ9AaXmN//F7NE33b6myXE3RCW+t+r2mRbX8vtAducMJh5zKMAGj7bT/k81oerT5sOS/IYfZwuNHnhCbELSpe8Eaun6yfPrtMKAZMc1IiKB9Q7egQYWecnf7F9KWxgre3zNHsnxHND1fJi6TjoyWs/9/mTCz9sdlqcP22j/hg/dP+UljCsxhz2Y5rlxkcTRz6/zYCa2tucchry5DvM2l9hgbeK3j+ZfnOB2LAjrLS4wgZW8UEE/J8AjMBuVL0GCKofEW50V++mRI9HdW4TgZQEFMBkVFE8DjYwzBkKSJnS8ixQ8qxpazVsPTLS9x7vzr/Z25Gb8/mZUMQGuJD6ewRieTzIyPyqc9HZDL7F1mMPf1+/tGk/ViIz0MXvokkNlV1y4Nad9L365OE0U8d8sRwFZ51WklEL7dk5iThOYo8VrNxYoEZ4lEBi4xk0vNS8Z3RGkayAGGx4tWtt+uw2udlqHAqwv2Yfg6gMcJVblDr7RQOJsmj/2Z+RG10IKfJZKZ65OA0SPGeNmM7CnQ1e4eSKWLABixkLmhnjCXcFdXyOJx5VKazlHIkwLHgw2yqdc+fC0xW6gLOaiTpeHZECZP9DEkK6Rj8ZMd3MOzOPwxA/0kTmYUflzoZZjs2erg=
  app: powerful-fortress-73868
  on:
    repo: esokoletsky/node-shopping-list-integration-tests
